### Always start with this!

In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


#### Numerical Tests

In [2]:
1 < 2 

True

In [3]:
3 >= 4

False

In [4]:
2*5 == 10

True

### Slicing

You can "slice" a list:

In [13]:
my_list = ['a', 'b', 'c', 'd', 'e']
my_list[1:3]  # Take elements 1 ('b') to 3 ('d'), not including the last

['b', 'c']

If you leave out the first index before the colon, it assumes element 0:

In [14]:
my_list[:3]  # Take elements 0 ('a') to 3 ('d'), not including the last

['a', 'b', 'c']

If you leave out the last index after the colon, it assumes all the way to the end:

In [15]:
my_list[3:]  # Take elements 3 ('d') all the way to the end

['d', 'e']

### Advanced Slicing

With *arrays*, you can do fancy indexing.

In [16]:
my_array = array([10,20,30,40,50,60])

indices = [0, 4]

my_array[indices]  # Takes elements 0 (10) and 4 (50)

array([10, 50])

You can also use an array of Booleans (`True` or `False`):

In [20]:
indices = array([True, False, False, False, True, False])
my_array[indices]

array([10, 50])

You can generate this array of booleans with Boolean Tests on arrays:

In [23]:
my_array % 20 == 0

array([False,  True, False,  True, False,  True], dtype=bool)

In [24]:
indices = my_array % 20 == 0
my_array[indices]

array([20, 40, 60])

### If Statements

In [25]:
n = 4
if n <= 4:
    print('n ≤ 4')

n ≤ 4


You can have as much as you want in the body of an `if` statement, as long as its properly indented:

In [28]:
n = 4
if n <= 4:
    print('n ≤ 4')
    print('This is still in the if statement')
    print('if n > 4, you would not see this!')

n ≤ 4
This is still in the if statement
if n > 4, you would not see this!


An `if` statement can optionally have `elif` (short for "else if") statements, which are additional tests. Only one `if` or `elif` can "trigger".

There can optionally also be an `else` statement. With an `else` statement, exactly *one* of the `if`, `elif`, or `else` clauses will "trigger".

In [29]:
n = 20
if n <= 4:
    print('n ≤ 4')
elif n <= 10:
    print('4 < n ≤ 10')
elif n <= 20:
    print('10 < n ≤ 20')
else:
    print('20 < n')

10 < n ≤ 20


### For loops

A `for` loop allows you to run some code for *every* element in a list.

In [31]:
for n in [1, 2, 3]:
    m = n * 2
    print(n, '* 2 =', m)

1 * 2 = 2
2 * 2 = 4
3 * 2 = 6


You can iterate over many things in Python, including arrays and strings:

In [32]:
my_array = linspace(0, 20, 5)
for n in my_array:
    print(n, 'is in my_array')
    
my_string = 'STRING!!!'
for c in my_string:
    print(c, 'is in my_string')

0.0 is in my_array
5.0 is in my_array
10.0 is in my_array
15.0 is in my_array
20.0 is in my_array
S is in my_string
T is in my_string
R is in my_string
I is in my_string
N is in my_string
G is in my_string
! is in my_string
! is in my_string
! is in my_string
